package com.softserve.edu.entity.util;

public enum Status {
    SENT, ACCEPTED, REJECTED, IN_PROGRESS, TEST_PLACE_DETERMINED, 
    SENT_TO_TEST_DEVICE, TEST_COMPLETED, SENT_TO_VERIFICATOR, TEST_OK, TEST_NOK
}
